# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/docs/sushi/configuration/                    │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: SHIFT-Task-Force.privacy.examples
canonical: http://SHIFT-Task-Force.github.io/demo-fhir-data
name: ShiftPrivacyExamples
title: "SHIFT Privacy Examples"
description: "A FHIR Implementation Guide containing example FHIR resources demonstrating privacy labeling using Security Labels and example ValueSets for sensitive data."
status: active
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2025+
releaseLabel: ci-build
publisher:
  name: SHIFT-Task-Force
  url: http://shift-project.org
license: CC-BY-4.0
jurisdiction: 'http://unstats.un.org/unsd/methods/m49/m49.htm#001'

parameters:  # see https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
  path-resource:
    - fsh-generated/resources
#  path-pages:
#    - input/pagecontent
#    - fsh-generated/includes
  show-inherited-invariants: 'false'
  usage-stats-opt-out: 'false'
  logging: progress
  shownav: 'true'
  active-tables: 'false'
  apply-contact: 'true'
  apply-jurisdiction: 'true'
  apply-publisher: 'true'
  apply-version: 'true'

## vsac Must use 0.19.0 as higher versions removed the SAMHSA valueSets
dependencies:
  us.nlm.vsac: 
    uri: http://fhir.org/packages/us.nlm.vsac/ImplementationGuide/us.nlm.vsac
    version: 0.19.0
#    version: 0.24.0

#dependencies:
#  hl7.fhir.us.core: 4.0.0
#  hl7.fhir.us.core: current
#  ihe.iti.pcf: 1.1.0
#  hl7.xprod.uv.gender-harmony: current

# ╭────────────────────────────────────────────pages───────────────────────────────────────────────╮
# │  The pages property corresponds to IG.definition.page.                                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
pages:
  index.md:
    title: "SHIFT IG Home"
  behavioral.md:
    title: "Behavioral Health Use Case"
  adolescent.md:
    title: "Adolescent Use Case"
  monica.md:
    title: "Monica Rambeau"
  monica19.md:
    title: "Monica at 19"
  monica16.md:
    title: "Monica at 16"
  download.md:
    title: "About and Download"


# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Use-Cases:
    Adolescent: adolescent.html
    Behavioral-Health: behavioral.html
    Monica: monica.html
  Artifacts: artifacts.html
  About: download.html

groups:
  CarlFredericksonCareTeam:
    description: "Resources related to Carl Frederickson's Care Team"
    resources:
      - PractitionerRole/DrHibbert-pcp
      - Practitioner/DrHibbert
      - Organization/SpringfieldMedicalCenter
      - PractitionerRole/DrFunke-psychiatrist
      - Practitioner/DrFunke
      - PractitionerRole/LucyvanPelt-therapist
      - Practitioner/LucyvanPelt
      - PractitionerRole/DrWhite-psychiatrist
      - Practitioner/DrWhite
      - Organization/SpringfieldMedicalCenterAddictionProgram
      - Organization/OrthopedicHealthServices
      - PractitionerRole/DrSasquatch-podiatrist
      - Practitioner/DrSasquatch
      - Organization/RegionalAdvancedDiagnosticServices
      - PractitionerRole/DrBanner-radiologist
      - Practitioner/DrBanner
      - PractitionerRole/DrAurora-anesthesiologist
      - Practitioner/DrAurora
      - PractitionerRole/ACOCareManager-practitionerrole
      - Practitioner/ACO-Care-Manager
      - Organization/SpringfieldACO
      - Bundle/AllofCarlTeam
  CarlFrederickson:
    description: "Resources related to Carl Frederickson"
    resources:
      - Patient/CarlFrederickson
      - CareTeam/CarlFredericksonCareTeam
      - Observation/CarlFredericksonPHQ9
      - Observation/CarlFredericksonPHQ9A  
      - Condition/CarlFredericksonBunions
      - Condition/CarlFredericksonHTN
      - Condition/CarlFredericksonMDD
      - Condition/CarlFredericksonOCPD
      - Condition/CarlFredericksonOUD
      - DiagnosticReport/CarlFredericksonXrayFeet
      - MedicationRequest/CarlFredericksonBuprenorphineNaltrexone
      - MedicationRequest/CarlFredericksonCaptopril
      - MedicationRequest/CarlFredericksonFluoxetine
      - MedicationRequest/CarlFredericksonIbuprofen
      - Observation/CarlFredericksonBloodPressure
      - Observation/CarlFredericksonOUDThoughtRecord
      - RelatedPerson/EllieFrederickson
      - Bundle/AllOfCarlFrederickson

      

